
declare module "*express"
declare module "*process"
declare module "*mongoose"
declare module "*cors"
declare module "*bcrypt"
declare module "*jsonwebtoken"
declare module "*path"
declare module "*multer"
declare module "*cloudinary"
declare module "*flutterwave-node-v3"
declare module "*uuid"
declare module "*nodemailer"
declare module "*ejs"
declare module "*googleapis"

